#
# Merge fixes from the latest release branch into the master branch
#
name: create-master-merge-pr

on:
  # Can be triggered manually
  workflow_dispatch:
  # Run on a schedule (every Monday morning)
  schedule:
    - cron: '30 6 * * MON'

jobs:
  create-merge-pr:
    env:
      MERGE_BASE: master
      MERGE_FROM: gvmd-20.08
      MERGE_INTO: auto-merge-into-master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch ${{ env.MERGE_BASE }}
        id: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.MERGE_BASE }}
          fetch-depth: 0 
      - name: Push to pull request branch ${{ env.MERGE_INTO }}
        id: push_pr_branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.MERGE_INTO }}
          force: true 
      - name: Merge branch ${{ env.MERGE_FROM }}
        id: merge
        uses: everlytic/branch-merge@1.1.0
        with: 
          source_ref: ${{ env.MERGE_FROM }}
          target_branch: ${{ env.MERGE_INTO }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message_template: "Automatic merge of ${{ env.MERGE_FROM }} into ${{ env.MERGE_BASE }}"
      - name: Count commits 
        id: count_commits
        run: 'git fetch && echo ::set-output name=commits::$(git log --no-merges --oneline ..origin/${{ env.MERGE_INTO }} -- | wc -l)'
      - name: Create pull request
        id: create_pr
        if: ${{ steps.count_commits.outputs.commits > 0 }}
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          title: "Merge ${{ env.MERGE_FROM }} into ${{ env.MERGE_BASE }}"
          body: "This automatically generated PR
                 merges ${{ steps.count_commits.outputs.commits }} commit(s)
                 from the ${{ env.MERGE_FROM }} branch into ${{ env.MERGE_BASE }}."
          base: ${{ env.MERGE_BASE }}
          head: ${{ env.MERGE_INTO }}
